package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 16 18:08:07 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DivisionsViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public DivisionsViewImpl() {
    }
    
    public String retrieveDivisionsFirstParentId() {
        return (String)callStoredFunction(VARCHAR2,"UTILITY.retrieve_division_parentid", new Object[] {});
    }
}

