package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 28 15:30:59 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KassaSettingsViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public KassaSettingsViewImpl() {
    }


    /**
     * Returns the variable value for user_id.
     * @return variable value for user_id
     */
    public String getuser_id() {
        return (String) ensureVariableManager().getVariableValue("user_id");
    }

    /**
     * Sets <code>value</code> for variable user_id.
     * @param value value to bind as user_id
     */
    public void setuser_id(String value) {
        ensureVariableManager().setVariableValue("user_id", value);
    }
}

