package ua.divas.view;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.server.Entity;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jbo.server.ViewRowSetImpl;

import ua.divas.classes.DivasView;
import ua.divas.classes.IndexCharacterObject;
import ua.divas.view.common.KontragentsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 24 20:28:58 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KontragentsViewImpl extends DivasView implements KontragentsView {
    /**
     * This is the default constructor (do not remove).
     */
    public KontragentsViewImpl() {
    }

    public String retrieveCustomersFirstParentId() {
        String rv = getCustomerParentId();
        if (rv != null) {
            return rv;
        }
        /* ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("KontragentsView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo.findByViewCriteria(this.getViewCriteria("KontragentsCustomerParentGroup"), -1,
                                                   this.QUERY_MODE_SCAN_DATABASE_TABLES);
        Row row = rs.first();
        if (row != null) {
            rv = (String) row.getAttribute("Id");
            return rv;
        }*/
        return null; 
    }
    
    public String retrieveCustomersFirstParentName() {
        String rv = getCustomerParentName();
        if (rv != null) {
            return rv;
        }
        /* ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("KontragentsView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo.findByViewCriteria(this.getViewCriteria("KontragentsCustomerParentGroup"), -1,
                                                   this.QUERY_MODE_SCAN_DATABASE_TABLES);
        Row row = rs.first();
        if (row != null) {
            rv = (String) row.getAttribute("Id");
            return rv;
        }*/
        return null; 
    }

    public String getRowStatus(Row row) {
        KontragentsViewRowImpl rwImpl = (KontragentsViewRowImpl) row;
        String rwStatus = translateStatusToString(rwImpl.getEntity(0).getEntityState());
        return rwStatus;
    }

    private String translateStatusToString(byte b) {
        String ret = null;
        switch (b) {
        case Entity.STATUS_INITIALIZED:
            {
                ret = "Initialized";
                break;
            }
        case Entity.STATUS_MODIFIED:
            {
                ret = "Modified";
                break;
            }
        case Entity.STATUS_UNMODIFIED:
            {
                ret = "Unmodified";
                break;
            }
        case Entity.STATUS_NEW:
            {
                ret = "New";
                break;
            }
        }
        return ret;
    }

    public List<IndexCharacterObject> getCharacterIndexList() {
        String[] alphabet = {
            "А", "Б", "В", "Г", "Д", "Е", "Ё", "Ж", "З", "И", "Й", "К", "Л", "М", "Н", "О", "П", "Р", "С", "Т", "У",
            "Ф", "Х", "Ч", "Ш", "Щ", "Э", "Ю", "Я"
        };
        //list that contains 26 entries
        List<IndexCharacterObject> list = new ArrayList<IndexCharacterObject>();
        //a list of all in  itial characters that are found in the row set
        //last_name attribute
        HashMap map = new HashMap();
        RowSet rs = this.getRowSet();
        this.executeQuery();
        Row row = rs.first();

        //query all rows and memorize the initial characters of
        //all employees last name entries
        if (row != null) {
            //Optionally, change "LastName" to another column attribute name
            //to change the search attribute
            String lastname = (String) row.getAttribute("Fullname");
            String character = lastname.toUpperCase().substring(0, 1);
            updateMap(map, row, character);
            while (rs.hasNext()) {
                row = rs.next();
                character = ((String) row.getAttribute("Fullname")).toUpperCase().substring(0, 1);
                updateMap(map, row, character);
            }
        }

        for (int i = 0; i < alphabet.length; ++i) {
            if (map.containsKey(alphabet[i].toUpperCase())) {
                IndexCharacterObject ico = new IndexCharacterObject();
                ico.setCharacter(alphabet[i].toUpperCase());
                ico.setFound(true);
                //  get rowIndex from map
                ico.setRowIndex(((Key) map.get((alphabet[i].toUpperCase()))));
                list.add(i, ico);
            } else {
                IndexCharacterObject ico = new IndexCharacterObject();
                ico.setCharacter(alphabet[i].toUpperCase());
                ico.setFound(false);
                //get rowIndex from map
                ico.setRowIndex(null);
                list.add(i, ico);
            }
            rs.first();
        }
        return list;
    }

    private void updateMap(HashMap map, Row row, String character) {
        if (!map.containsKey(character)) {
            //remember character and first occurrence in rowSet
            map.put(character, row.getKey());
        }
    }

}

