package ua.divas.view;

import java.io.IOException;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.WLS_Utility;
import ua.divas.view.common.UsersView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 21 15:52:50 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsersViewImpl extends ViewObjectImpl implements UsersView {
    /**
     * This is the default constructor (do not remove).
     */
    public UsersViewImpl() {
    }

    public void addUserToWls(String username, String psw, String desc) {
        try {
            WLS_Utility.addUser(username, psw, desc);
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    public void changeUserPwdToWls(String username, String oldPassword, String newPassword) {
        try {
            WLS_Utility.changeUserPassword(username, oldPassword, newPassword);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void resetUserPwdToWls(String username, String newPassword) {
        WLS_Utility.resetUserPassword(username, newPassword);
    }
}

