package ua.divas.view;

import java.sql.SQLException;

import java.util.Calendar;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 16 20:04:09 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwBallansApDetailImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VwBallansApDetailImpl() {
    }
    
    public Date getDateLast() throws SQLException {
        Calendar calendar = Calendar.getInstance();
        //calendar.set(Calendar.DAY_OF_MONTH, calendar.getActualMinimum(Calendar.DAY_OF_MONTH)); // это будет начало месяца
        //calendar.set(Calendar.DAY_OF_MONTH, calendar.getActualMaximum(Calendar.DAY_OF_MONTH)); // это будет конец месяца
        //calendar.set(Calendar.DAY_OF_YEAR, calendar.getActualMaximum(Calendar.DAY_OF_YEAR)); // это будет конец года
        calendar.set(Calendar.DAY_OF_YEAR, calendar.getActualMinimum(Calendar.DAY_OF_YEAR)); // это будет начало года
        java.util.Date pDate = calendar.getTime();
        oracle.jbo.domain.Date dbDate= new oracle.jbo.domain.Date(new java.sql.Date(pDate.getTime()));
        //oracle.jbo.domain.Date time = new oracle.jbo.domain.Date(pDate);
        return dbDate;
    }

    /**
     * Returns the bind variable value for f_dat.
     * @return bind variable value for f_dat
     */
    public Date getf_dat() {
        return (Date) getNamedWhereClauseParam("f_dat");
    }

    /**
     * Sets <code>value</code> for bind variable f_dat.
     * @param value value to bind as f_dat
     */
    public void setf_dat(Date value) {
        setNamedWhereClauseParam("f_dat", value);
    }

    /**
     * Returns the bind variable value for l_dat.
     * @return bind variable value for l_dat
     */
    public Date getl_dat() {
        return (Date) getNamedWhereClauseParam("l_dat");
    }

    /**
     * Sets <code>value</code> for bind variable l_dat.
     * @param value value to bind as l_dat
     */
    public void setl_dat(Date value) {
        setNamedWhereClauseParam("l_dat", value);
    }
}

