package ua.divas.view;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
import ua.divas.view.common.VwKontragZamer;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 20 21:09:10 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwKontragZamerImpl extends DivasView implements VwKontragZamer {

    public void paySelectedRows() {
        RowSet duplicateRowSet = this.createRowSet("duplicateRowSet");
        duplicateRowSet.first();
        Row currentRow = this.getCurrentRow();
        boolean currentRowDeleted = false;
        Row[] rowsToDelete = duplicateRowSet.getFilteredRows("MarkedForPaymant", true);
        if (rowsToDelete.length > 0) {
            for (Row rw : rowsToDelete) {
                if (rw.getKey().equals(currentRow.getKey())) {
                    currentRowDeleted = true;
                }
               // rw.remove();
            }
            this.executeQuery();
            if (!currentRowDeleted) {
                this.setCurrentRow(currentRow);
            }
            duplicateRowSet.closeRowSet();
        }
    }

    /**
     * This is the default constructor (do not remove).
     */
    public VwKontragZamerImpl() {
    }

    /**
     * Returns the bind variable value for u_name.
     * @return bind variable value for u_name
     */
    public String getu_name() {
        return (String) getNamedWhereClauseParam("u_name");
    }

    /**
     * Sets <code>value</code> for bind variable u_name.
     * @param value value to bind as u_name
     */
    public void setu_name(String value) {
        setNamedWhereClauseParam("u_name", value);
    }
}

