package ua.divas.module;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;


import oracle.jbo.server.ViewObjectImpl;

import ua.divas.module.common.AppModule;
import ua.divas.view.CompaignsViewImpl;
import ua.divas.view.ContactDetailsViewImpl;
import ua.divas.view.CurrencyViewImpl;
import ua.divas.view.DivisionsViewImpl;
import ua.divas.view.FirmsViewImpl;
import ua.divas.view.GroupmembersViewImpl;
import ua.divas.view.KassaVOImpl;
import ua.divas.view.KontragentsViewImpl;
import ua.divas.view.ro.KontragentsItemsLookupVOImpl;
import ua.divas.view.ro.UsersItemsLookupVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 06 16:15:08 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for CallLogView1.
     * @return CallLogView1
     */
    public ViewObjectImpl getCallLogView1() {
        return (ViewObjectImpl) findViewObject("CallLogView1");
    }

    /**
     * Container's getter for CallResultsView1.
     * @return CallResultsView1
     */
    public ViewObjectImpl getCallResultsView1() {
        return (ViewObjectImpl) findViewObject("CallResultsView1");
    }

    /**
     * Container's getter for CallStatusView1.
     * @return CallStatusView1
     */
    public ViewObjectImpl getCallStatusView1() {
        return (ViewObjectImpl) findViewObject("CallStatusView1");
    }

    /**
     * Container's getter for CompaignsDetailsView1.
     * @return CompaignsDetailsView1
     */
    public ViewObjectImpl getCompaignsDetailsView1() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView1");
    }

    /**
     * Container's getter for CompaignsView1.
     * @return CompaignsView1
     */
    public CompaignsViewImpl getCompaignsView1() {
        return (CompaignsViewImpl) findViewObject("CompaignsView1");
    }

    /**
     * Container's getter for ContactDetailsView1.
     * @return ContactDetailsView1
     */
    public ContactDetailsViewImpl getContactDetailsView1() {
        return (ContactDetailsViewImpl) findViewObject("ContactDetailsView1");
    }

    /**
     * Container's getter for CurrencyView1.
     * @return CurrencyView1
     */
    public CurrencyViewImpl getCurrencyView1() {
        return (CurrencyViewImpl) findViewObject("CurrencyView1");
    }

    /**
     * Container's getter for DivisionsView1.
     * @return DivisionsView1
     */
    public DivisionsViewImpl getDivisionsView1() {
        return (DivisionsViewImpl) findViewObject("DivisionsView1");
    }

    /**
     * Container's getter for EntrySettingsView1.
     * @return EntrySettingsView1
     */
    public ViewObjectImpl getEntrySettingsView1() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView1");
    }

    /**
     * Container's getter for EnumAccountTypeView1.
     * @return EnumAccountTypeView1
     */
    public ViewObjectImpl getEnumAccountTypeView1() {
        return (ViewObjectImpl) findViewObject("EnumAccountTypeView1");
    }

    /**
     * Container's getter for ExRatesSettingsView1.
     * @return ExRatesSettingsView1
     */
    public ViewObjectImpl getExRatesSettingsView1() {
        return (ViewObjectImpl) findViewObject("ExRatesSettingsView1");
    }

    /**
     * Container's getter for FirmsView1.
     * @return FirmsView1
     */
    public FirmsViewImpl getFirmsView1() {
        return (FirmsViewImpl) findViewObject("FirmsView1");
    }

    /**
     * Container's getter for GroupsView1.
     * @return GroupsView1
     */
    public ViewObjectImpl getGroupsView1() {
        return (ViewObjectImpl) findViewObject("GroupsView1");
    }

    /**
     * Container's getter for KassaView1.
     * @return KassaView1
     */
    public ViewObjectImpl getKassaView1() {
        return (ViewObjectImpl) findViewObject("KassaView1");
    }

    /**
     * Container's getter for KontragentsView1.
     * @return KontragentsView1
     */
    public KontragentsViewImpl getKontragentsView1() {
        return (KontragentsViewImpl) findViewObject("KontragentsView1");
    }

    /**
     * Container's getter for MeasureUnitView1.
     * @return MeasureUnitView1
     */
    public ViewObjectImpl getMeasureUnitView1() {
        return (ViewObjectImpl) findViewObject("MeasureUnitView1");
    }

    /**
     * Container's getter for MovesView1.
     * @return MovesView1
     */
    public ViewObjectImpl getMovesView1() {
        return (ViewObjectImpl) findViewObject("MovesView1");
    }

    /**
     * Container's getter for NomenklaturaView1.
     * @return NomenklaturaView1
     */
    public ViewObjectImpl getNomenklaturaView1() {
        return (ViewObjectImpl) findViewObject("NomenklaturaView1");
    }

    /**
     * Container's getter for NumeratorView1.
     * @return NumeratorView1
     */
    public ViewObjectImpl getNumeratorView1() {
        return (ViewObjectImpl) findViewObject("NumeratorView1");
    }

    /**
     * Container's getter for OrderStatusView1.
     * @return OrderStatusView1
     */
    public ViewObjectImpl getOrderStatusView1() {
        return (ViewObjectImpl) findViewObject("OrderStatusView1");
    }

    /**
     * Container's getter for OrdersView1.
     * @return OrdersView1
     */
    public ViewObjectImpl getOrdersView1() {
        return (ViewObjectImpl) findViewObject("OrdersView1");
    }

    /**
     * Container's getter for PlanAccSubcontoView1.
     * @return PlanAccSubcontoView1
     */
    public ViewObjectImpl getPlanAccSubcontoView1() {
        return (ViewObjectImpl) findViewObject("PlanAccSubcontoView1");
    }

    /**
     * Container's getter for PlanAccView1.
     * @return PlanAccView1
     */
    public ViewObjectImpl getPlanAccView1() {
        return (ViewObjectImpl) findViewObject("PlanAccView1");
    }

    /**
     * Container's getter for PlanTypeSubcontoView1.
     * @return PlanTypeSubcontoView1
     */
    public ViewObjectImpl getPlanTypeSubcontoView1() {
        return (ViewObjectImpl) findViewObject("PlanTypeSubcontoView1");
    }

    /**
     * Container's getter for RegRatesView1.
     * @return RegRatesView1
     */
    public ViewObjectImpl getRegRatesView1() {
        return (ViewObjectImpl) findViewObject("RegRatesView1");
    }

    /**
     * Container's getter for TypeDefView1.
     * @return TypeDefView1
     */
    public ViewObjectImpl getTypeDefView1() {
        return (ViewObjectImpl) findViewObject("TypeDefView1");
    }

    /**
     * Container's getter for TypeOfActivitiesView1.
     * @return TypeOfActivitiesView1
     */
    public ViewObjectImpl getTypeOfActivitiesView1() {
        return (ViewObjectImpl) findViewObject("TypeOfActivitiesView1");
    }

    /**
     * Container's getter for UserSettingsView1.
     * @return UserSettingsView1
     */
    public ViewObjectImpl getUserSettingsView1() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1");
    }

    /**
     * Container's getter for UsersGroupsView1.
     * @return UsersGroupsView1
     */
    public ViewObjectImpl getUsersGroupsView1() {
        return (ViewObjectImpl) findViewObject("UsersGroupsView1");
    }

    /**
     * Container's getter for UsersView1.
     * @return UsersView1
     */
    public ViewObjectImpl getUsersView1() {
        return (ViewObjectImpl) findViewObject("UsersView1");
    }

    /**
     * Container's getter for VoucherView1.
     * @return VoucherView1
     */
    public ViewObjectImpl getVoucherView1() {
        return (ViewObjectImpl) findViewObject("VoucherView1");
    }

    /**
     * Container's getter for ZatratyView1.
     * @return ZatratyView1
     */
    public ViewObjectImpl getZatratyView1() {
        return (ViewObjectImpl) findViewObject("ZatratyView1");
    }

    /**
     * Container's getter for CallLogView1_1.
     * @return CallLogView1_1
     */
    public ViewObjectImpl getCallLogView1_1() {
        return (ViewObjectImpl) findViewObject("CallLogView1_1");
    }

    /**
     * Container's getter for CallResultsView1_1.
     * @return CallResultsView1_1
     */
    public ViewObjectImpl getCallResultsView1_1() {
        return (ViewObjectImpl) findViewObject("CallResultsView1_1");
    }

    /**
     * Container's getter for CallStatusView1_1.
     * @return CallStatusView1_1
     */
    public ViewObjectImpl getCallStatusView1_1() {
        return (ViewObjectImpl) findViewObject("CallStatusView1_1");
    }

    /**
     * Container's getter for CompaignsView1_1.
     * @return CompaignsView1_1
     */
    public ViewObjectImpl getCompaignsView1_1() {
        return (ViewObjectImpl) findViewObject("CompaignsView1_1");
    }

    /**
     * Container's getter for CompaignsDetailsView1_1.
     * @return CompaignsDetailsView1_1
     */
    public ViewObjectImpl getCompaignsDetailsView1_1() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView1_1");
    }

    /**
     * Container's getter for ContactDetailsView1_1.
     * @return ContactDetailsView1_1
     */
    public ViewObjectImpl getContactDetailsView1_1() {
        return (ViewObjectImpl) findViewObject("ContactDetailsView1_1");
    }

    /**
     * Container's getter for CurrencyView1_1.
     * @return CurrencyView1_1
     */
    public ViewObjectImpl getCurrencyView1_1() {
        return (ViewObjectImpl) findViewObject("CurrencyView1_1");
    }

    /**
     * Container's getter for DivisionsView1_1.
     * @return DivisionsView1_1
     */
    public ViewObjectImpl getDivisionsView1_1() {
        return (ViewObjectImpl) findViewObject("DivisionsView1_1");
    }

    /**
     * Container's getter for EntrySettingsView1_1.
     * @return EntrySettingsView1_1
     */
    public ViewObjectImpl getEntrySettingsView1_1() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView1_1");
    }

    /**
     * Container's getter for EnumAccountTypeView1_1.
     * @return EnumAccountTypeView1_1
     */
    public ViewObjectImpl getEnumAccountTypeView1_1() {
        return (ViewObjectImpl) findViewObject("EnumAccountTypeView1_1");
    }

    /**
     * Container's getter for ExRatesSettingsView1_1.
     * @return ExRatesSettingsView1_1
     */
    public ViewObjectImpl getExRatesSettingsView1_1() {
        return (ViewObjectImpl) findViewObject("ExRatesSettingsView1_1");
    }

    /**
     * Container's getter for FirmsView1_1.
     * @return FirmsView1_1
     */
    public ViewObjectImpl getFirmsView1_1() {
        return (ViewObjectImpl) findViewObject("FirmsView1_1");
    }

    /**
     * Container's getter for GroupsView1_1.
     * @return GroupsView1_1
     */
    public ViewObjectImpl getGroupsView1_1() {
        return (ViewObjectImpl) findViewObject("GroupsView1_1");
    }

    /**
     * Container's getter for KassaView1_1.
     * @return KassaView1_1
     */
    public ViewObjectImpl getKassaView1_1() {
        return (ViewObjectImpl) findViewObject("KassaView1_1");
    }

    /**
     * Container's getter for KontragentsView1_1.
     * @return KontragentsView1_1
     */
    public ViewObjectImpl getKontragentsView1_1() {
        return (ViewObjectImpl) findViewObject("KontragentsView1_1");
    }

    /**
     * Container's getter for MeasureUnitView1_1.
     * @return MeasureUnitView1_1
     */
    public ViewObjectImpl getMeasureUnitView1_1() {
        return (ViewObjectImpl) findViewObject("MeasureUnitView1_1");
    }

    /**
     * Container's getter for MovesView1_1.
     * @return MovesView1_1
     */
    public ViewObjectImpl getMovesView1_1() {
        return (ViewObjectImpl) findViewObject("MovesView1_1");
    }

    /**
     * Container's getter for NomenklaturaView1_1.
     * @return NomenklaturaView1_1
     */
    public ViewObjectImpl getNomenklaturaView1_1() {
        return (ViewObjectImpl) findViewObject("NomenklaturaView1_1");
    }

    /**
     * Container's getter for NumeratorView1_1.
     * @return NumeratorView1_1
     */
    public ViewObjectImpl getNumeratorView1_1() {
        return (ViewObjectImpl) findViewObject("NumeratorView1_1");
    }

    /**
     * Container's getter for OrdersView1_1.
     * @return OrdersView1_1
     */
    public ViewObjectImpl getOrdersView1_1() {
        return (ViewObjectImpl) findViewObject("OrdersView1_1");
    }

    /**
     * Container's getter for OrderStatusView1_1.
     * @return OrderStatusView1_1
     */
    public ViewObjectImpl getOrderStatusView1_1() {
        return (ViewObjectImpl) findViewObject("OrderStatusView1_1");
    }

    /**
     * Container's getter for PlanAccView1_1.
     * @return PlanAccView1_1
     */
    public ViewObjectImpl getPlanAccView1_1() {
        return (ViewObjectImpl) findViewObject("PlanAccView1_1");
    }

    /**
     * Container's getter for PlanAccSubcontoView1_1.
     * @return PlanAccSubcontoView1_1
     */
    public ViewObjectImpl getPlanAccSubcontoView1_1() {
        return (ViewObjectImpl) findViewObject("PlanAccSubcontoView1_1");
    }

    /**
     * Container's getter for PlanTypeSubcontoView1_1.
     * @return PlanTypeSubcontoView1_1
     */
    public ViewObjectImpl getPlanTypeSubcontoView1_1() {
        return (ViewObjectImpl) findViewObject("PlanTypeSubcontoView1_1");
    }

    /**
     * Container's getter for RegRatesView1_1.
     * @return RegRatesView1_1
     */
    public ViewObjectImpl getRegRatesView1_1() {
        return (ViewObjectImpl) findViewObject("RegRatesView1_1");
    }

    /**
     * Container's getter for TypeDefView1_1.
     * @return TypeDefView1_1
     */
    public ViewObjectImpl getTypeDefView1_1() {
        return (ViewObjectImpl) findViewObject("TypeDefView1_1");
    }

    /**
     * Container's getter for TypeOfActivitiesView1_1.
     * @return TypeOfActivitiesView1_1
     */
    public ViewObjectImpl getTypeOfActivitiesView1_1() {
        return (ViewObjectImpl) findViewObject("TypeOfActivitiesView1_1");
    }

    /**
     * Container's getter for UsersView1_1.
     * @return UsersView1_1
     */
    public ViewObjectImpl getUsersView1_1() {
        return (ViewObjectImpl) findViewObject("UsersView1_1");
    }

    /**
     * Container's getter for UsersGroupsView1_1.
     * @return UsersGroupsView1_1
     */
    public ViewObjectImpl getUsersGroupsView1_1() {
        return (ViewObjectImpl) findViewObject("UsersGroupsView1_1");
    }

    /**
     * Container's getter for UserSettingsView1_1.
     * @return UserSettingsView1_1
     */
    public ViewObjectImpl getUserSettingsView1_1() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_1");
    }

    /**
     * Container's getter for VoucherView1_1.
     * @return VoucherView1_1
     */
    public ViewObjectImpl getVoucherView1_1() {
        return (ViewObjectImpl) findViewObject("VoucherView1_1");
    }

    /**
     * Container's getter for ZatratyView1_1.
     * @return ZatratyView1_1
     */
    public ViewObjectImpl getZatratyView1_1() {
        return (ViewObjectImpl) findViewObject("ZatratyView1_1");
    }

    /**
     * Container's getter for CallLogView2.
     * @return CallLogView2
     */
    public ViewObjectImpl getCallLogView2() {
        return (ViewObjectImpl) findViewObject("CallLogView2");
    }

    /**
     * Container's getter for CallLogView3.
     * @return CallLogView3
     */
    public ViewObjectImpl getCallLogView3() {
        return (ViewObjectImpl) findViewObject("CallLogView3");
    }

    /**
     * Container's getter for CompaignsDetailsView2.
     * @return CompaignsDetailsView2
     */
    public ViewObjectImpl getCompaignsDetailsView2() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView2");
    }

    /**
     * Container's getter for CallLogView4.
     * @return CallLogView4
     */
    public ViewObjectImpl getCallLogView4() {
        return (ViewObjectImpl) findViewObject("CallLogView4");
    }

    /**
     * Container's getter for CompaignsDetailsView3.
     * @return CompaignsDetailsView3
     */
    public ViewObjectImpl getCompaignsDetailsView3() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView3");
    }

    /**
     * Container's getter for DivisionsView2.
     * @return DivisionsView2
     */
    public DivisionsViewImpl getDivisionsView2() {
        return (DivisionsViewImpl) findViewObject("DivisionsView2");
    }

    /**
     * Container's getter for ExRatesSettingsView2.
     * @return ExRatesSettingsView2
     */
    public ViewObjectImpl getExRatesSettingsView2() {
        return (ViewObjectImpl) findViewObject("ExRatesSettingsView2");
    }

    /**
     * Container's getter for KassaView2.
     * @return KassaView2
     */
    public ViewObjectImpl getKassaView2() {
        return (ViewObjectImpl) findViewObject("KassaView2");
    }

    /**
     * Container's getter for KassaView3.
     * @return KassaView3
     */
    public ViewObjectImpl getKassaView3() {
        return (ViewObjectImpl) findViewObject("KassaView3");
    }

    /**
     * Container's getter for KassaView4.
     * @return KassaView4
     */
    public ViewObjectImpl getKassaView4() {
        return (ViewObjectImpl) findViewObject("KassaView4");
    }

    /**
     * Container's getter for KassaView5.
     * @return KassaView5
     */
    public ViewObjectImpl getKassaView5() {
        return (ViewObjectImpl) findViewObject("KassaView5");
    }

    /**
     * Container's getter for KontragentsView2.
     * @return KontragentsView2
     */
    public KontragentsViewImpl getKontragentsView2() {
        return (KontragentsViewImpl) findViewObject("KontragentsView2");
    }

    /**
     * Container's getter for CompaignsDetailsView4.
     * @return CompaignsDetailsView4
     */
    public ViewObjectImpl getCompaignsDetailsView4() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView4");
    }

    /**
     * Container's getter for ContactDetailsView2.
     * @return ContactDetailsView2
     */
    public ContactDetailsViewImpl getContactDetailsView2() {
        return (ContactDetailsViewImpl) findViewObject("ContactDetailsView2");
    }

    /**
     * Container's getter for MovesView2.
     * @return MovesView2
     */
    public ViewObjectImpl getMovesView2() {
        return (ViewObjectImpl) findViewObject("MovesView2");
    }

    /**
     * Container's getter for MovesView3.
     * @return MovesView3
     */
    public ViewObjectImpl getMovesView3() {
        return (ViewObjectImpl) findViewObject("MovesView3");
    }

    /**
     * Container's getter for NomenklaturaView2.
     * @return NomenklaturaView2
     */
    public ViewObjectImpl getNomenklaturaView2() {
        return (ViewObjectImpl) findViewObject("NomenklaturaView2");
    }

    /**
     * Container's getter for OrdersView2.
     * @return OrdersView2
     */
    public ViewObjectImpl getOrdersView2() {
        return (ViewObjectImpl) findViewObject("OrdersView2");
    }

    /**
     * Container's getter for OrdersView3.
     * @return OrdersView3
     */
    public ViewObjectImpl getOrdersView3() {
        return (ViewObjectImpl) findViewObject("OrdersView3");
    }

    /**
     * Container's getter for OrdersView4.
     * @return OrdersView4
     */
    public ViewObjectImpl getOrdersView4() {
        return (ViewObjectImpl) findViewObject("OrdersView4");
    }

    /**
     * Container's getter for OrdersView5.
     * @return OrdersView5
     */
    public ViewObjectImpl getOrdersView5() {
        return (ViewObjectImpl) findViewObject("OrdersView5");
    }

    /**
     * Container's getter for OrdersView6.
     * @return OrdersView6
     */
    public ViewObjectImpl getOrdersView6() {
        return (ViewObjectImpl) findViewObject("OrdersView6");
    }

    /**
     * Container's getter for OrdersView7.
     * @return OrdersView7
     */
    public ViewObjectImpl getOrdersView7() {
        return (ViewObjectImpl) findViewObject("OrdersView7");
    }

    /**
     * Container's getter for PlanAccView2.
     * @return PlanAccView2
     */
    public ViewObjectImpl getPlanAccView2() {
        return (ViewObjectImpl) findViewObject("PlanAccView2");
    }

    /**
     * Container's getter for MovesView4.
     * @return MovesView4
     */
    public ViewObjectImpl getMovesView4() {
        return (ViewObjectImpl) findViewObject("MovesView4");
    }

    /**
     * Container's getter for MovesView5.
     * @return MovesView5
     */
    public ViewObjectImpl getMovesView5() {
        return (ViewObjectImpl) findViewObject("MovesView5");
    }

    /**
     * Container's getter for EntrySettingsView2.
     * @return EntrySettingsView2
     */
    public ViewObjectImpl getEntrySettingsView2() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView2");
    }

    /**
     * Container's getter for EntrySettingsView3.
     * @return EntrySettingsView3
     */
    public ViewObjectImpl getEntrySettingsView3() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView3");
    }

    /**
     * Container's getter for PlanAccView3.
     * @return PlanAccView3
     */
    public ViewObjectImpl getPlanAccView3() {
        return (ViewObjectImpl) findViewObject("PlanAccView3");
    }

    /**
     * Container's getter for PlanAccSubcontoView2.
     * @return PlanAccSubcontoView2
     */
    public ViewObjectImpl getPlanAccSubcontoView2() {
        return (ViewObjectImpl) findViewObject("PlanAccSubcontoView2");
    }

    /**
     * Container's getter for PlanAccSubcontoView3.
     * @return PlanAccSubcontoView3
     */
    public ViewObjectImpl getPlanAccSubcontoView3() {
        return (ViewObjectImpl) findViewObject("PlanAccSubcontoView3");
    }

    /**
     * Container's getter for RegRatesView2.
     * @return RegRatesView2
     */
    public ViewObjectImpl getRegRatesView2() {
        return (ViewObjectImpl) findViewObject("RegRatesView2");
    }

    /**
     * Container's getter for MovesView6.
     * @return MovesView6
     */
    public ViewObjectImpl getMovesView6() {
        return (ViewObjectImpl) findViewObject("MovesView6");
    }

    /**
     * Container's getter for PlanTypeSubcontoView2.
     * @return PlanTypeSubcontoView2
     */
    public ViewObjectImpl getPlanTypeSubcontoView2() {
        return (ViewObjectImpl) findViewObject("PlanTypeSubcontoView2");
    }

    /**
     * Container's getter for NumeratorView2.
     * @return NumeratorView2
     */
    public ViewObjectImpl getNumeratorView2() {
        return (ViewObjectImpl) findViewObject("NumeratorView2");
    }

    /**
     * Container's getter for EntrySettingsView4.
     * @return EntrySettingsView4
     */
    public ViewObjectImpl getEntrySettingsView4() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView4");
    }

    /**
     * Container's getter for MovesView7.
     * @return MovesView7
     */
    public ViewObjectImpl getMovesView7() {
        return (ViewObjectImpl) findViewObject("MovesView7");
    }

    /**
     * Container's getter for OrdersView8.
     * @return OrdersView8
     */
    public ViewObjectImpl getOrdersView8() {
        return (ViewObjectImpl) findViewObject("OrdersView8");
    }

    /**
     * Container's getter for OrdersView9.
     * @return OrdersView9
     */
    public ViewObjectImpl getOrdersView9() {
        return (ViewObjectImpl) findViewObject("OrdersView9");
    }

    /**
     * Container's getter for UsersGroupsView2.
     * @return UsersGroupsView2
     */
    public ViewObjectImpl getUsersGroupsView2() {
        return (ViewObjectImpl) findViewObject("UsersGroupsView2");
    }

    /**
     * Container's getter for UsersGroupsView3.
     * @return UsersGroupsView3
     */
    public ViewObjectImpl getUsersGroupsView3() {
        return (ViewObjectImpl) findViewObject("UsersGroupsView3");
    }

    /**
     * Container's getter for UserSettingsView2.
     * @return UserSettingsView2
     */
    public ViewObjectImpl getUserSettingsView2() {
        return (ViewObjectImpl) findViewObject("UserSettingsView2");
    }

    /**
     * Container's getter for UserSettingsView3.
     * @return UserSettingsView3
     */
    public ViewObjectImpl getUserSettingsView3() {
        return (ViewObjectImpl) findViewObject("UserSettingsView3");
    }

    /**
     * Container's getter for UserSettingsView4.
     * @return UserSettingsView4
     */
    public ViewObjectImpl getUserSettingsView4() {
        return (ViewObjectImpl) findViewObject("UserSettingsView4");
    }

    /**
     * Container's getter for UserSettingsView5.
     * @return UserSettingsView5
     */
    public ViewObjectImpl getUserSettingsView5() {
        return (ViewObjectImpl) findViewObject("UserSettingsView5");
    }

    /**
     * Container's getter for UserSettingsView6.
     * @return UserSettingsView6
     */
    public ViewObjectImpl getUserSettingsView6() {
        return (ViewObjectImpl) findViewObject("UserSettingsView6");
    }

    /**
     * Container's getter for UserSettingsView7.
     * @return UserSettingsView7
     */
    public ViewObjectImpl getUserSettingsView7() {
        return (ViewObjectImpl) findViewObject("UserSettingsView7");
    }

    /**
     * Container's getter for UserSettingsView8.
     * @return UserSettingsView8
     */
    public ViewObjectImpl getUserSettingsView8() {
        return (ViewObjectImpl) findViewObject("UserSettingsView8");
    }

    /**
     * Container's getter for ZatratyView2.
     * @return ZatratyView2
     */
    public ViewObjectImpl getZatratyView2() {
        return (ViewObjectImpl) findViewObject("ZatratyView2");
    }

    /**
     * Container's getter for CallLogView1_2.
     * @return CallLogView1_2
     */
    public ViewObjectImpl getCallLogView1_2() {
        return (ViewObjectImpl) findViewObject("CallLogView1_2");
    }

    /**
     * Container's getter for CompaignsDetailsView1_2.
     * @return CompaignsDetailsView1_2
     */
    public ViewObjectImpl getCompaignsDetailsView1_2() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView1_2");
    }

    /**
     * Container's getter for CallLogView1_3.
     * @return CallLogView1_3
     */
    public ViewObjectImpl getCallLogView1_3() {
        return (ViewObjectImpl) findViewObject("CallLogView1_3");
    }

    /**
     * Container's getter for CallLogView1_4.
     * @return CallLogView1_4
     */
    public ViewObjectImpl getCallLogView1_4() {
        return (ViewObjectImpl) findViewObject("CallLogView1_4");
    }

    /**
     * Container's getter for CompaignsDetailsView1_3.
     * @return CompaignsDetailsView1_3
     */
    public ViewObjectImpl getCompaignsDetailsView1_3() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView1_3");
    }

    /**
     * Container's getter for ExRatesSettingsView1_2.
     * @return ExRatesSettingsView1_2
     */
    public ViewObjectImpl getExRatesSettingsView1_2() {
        return (ViewObjectImpl) findViewObject("ExRatesSettingsView1_2");
    }

    /**
     * Container's getter for KassaView1_2.
     * @return KassaView1_2
     */
    public ViewObjectImpl getKassaView1_2() {
        return (ViewObjectImpl) findViewObject("KassaView1_2");
    }

    /**
     * Container's getter for MovesView1_2.
     * @return MovesView1_2
     */
    public ViewObjectImpl getMovesView1_2() {
        return (ViewObjectImpl) findViewObject("MovesView1_2");
    }

    /**
     * Container's getter for MovesView1_3.
     * @return MovesView1_3
     */
    public ViewObjectImpl getMovesView1_3() {
        return (ViewObjectImpl) findViewObject("MovesView1_3");
    }

    /**
     * Container's getter for OrdersView1_2.
     * @return OrdersView1_2
     */
    public ViewObjectImpl getOrdersView1_2() {
        return (ViewObjectImpl) findViewObject("OrdersView1_2");
    }

    /**
     * Container's getter for RegRatesView1_2.
     * @return RegRatesView1_2
     */
    public ViewObjectImpl getRegRatesView1_2() {
        return (ViewObjectImpl) findViewObject("RegRatesView1_2");
    }

    /**
     * Container's getter for UserSettingsView1_2.
     * @return UserSettingsView1_2
     */
    public ViewObjectImpl getUserSettingsView1_2() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_2");
    }

    /**
     * Container's getter for DivisionsView1_2.
     * @return DivisionsView1_2
     */
    public ViewObjectImpl getDivisionsView1_2() {
        return (ViewObjectImpl) findViewObject("DivisionsView1_2");
    }

    /**
     * Container's getter for KassaView1_3.
     * @return KassaView1_3
     */
    public ViewObjectImpl getKassaView1_3() {
        return (ViewObjectImpl) findViewObject("KassaView1_3");
    }

    /**
     * Container's getter for OrdersView1_3.
     * @return OrdersView1_3
     */
    public ViewObjectImpl getOrdersView1_3() {
        return (ViewObjectImpl) findViewObject("OrdersView1_3");
    }

    /**
     * Container's getter for UserSettingsView1_3.
     * @return UserSettingsView1_3
     */
    public ViewObjectImpl getUserSettingsView1_3() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_3");
    }

    /**
     * Container's getter for PlanAccView1_2.
     * @return PlanAccView1_2
     */
    public ViewObjectImpl getPlanAccView1_2() {
        return (ViewObjectImpl) findViewObject("PlanAccView1_2");
    }

    /**
     * Container's getter for KassaView1_4.
     * @return KassaView1_4
     */
    public ViewObjectImpl getKassaView1_4() {
        return (ViewObjectImpl) findViewObject("KassaView1_4");
    }

    /**
     * Container's getter for OrdersView1_4.
     * @return OrdersView1_4
     */
    public ViewObjectImpl getOrdersView1_4() {
        return (ViewObjectImpl) findViewObject("OrdersView1_4");
    }

    /**
     * Container's getter for UserSettingsView1_4.
     * @return UserSettingsView1_4
     */
    public ViewObjectImpl getUserSettingsView1_4() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_4");
    }

    /**
     * Container's getter for UsersGroupsView1_2.
     * @return UsersGroupsView1_2
     */
    public ViewObjectImpl getUsersGroupsView1_2() {
        return (ViewObjectImpl) findViewObject("UsersGroupsView1_2");
    }

    /**
     * Container's getter for KassaView1_5.
     * @return KassaView1_5
     */
    public ViewObjectImpl getKassaView1_5() {
        return (ViewObjectImpl) findViewObject("KassaView1_5");
    }

    /**
     * Container's getter for OrdersView1_5.
     * @return OrdersView1_5
     */
    public ViewObjectImpl getOrdersView1_5() {
        return (ViewObjectImpl) findViewObject("OrdersView1_5");
    }

    /**
     * Container's getter for UserSettingsView1_5.
     * @return UserSettingsView1_5
     */
    public ViewObjectImpl getUserSettingsView1_5() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_5");
    }

    /**
     * Container's getter for CompaignsDetailsView1_4.
     * @return CompaignsDetailsView1_4
     */
    public ViewObjectImpl getCompaignsDetailsView1_4() {
        return (ViewObjectImpl) findViewObject("CompaignsDetailsView1_4");
    }

    /**
     * Container's getter for ContactDetailsView1_2.
     * @return ContactDetailsView1_2
     */
    public ViewObjectImpl getContactDetailsView1_2() {
        return (ViewObjectImpl) findViewObject("ContactDetailsView1_2");
    }

    /**
     * Container's getter for KontragentsView1_2.
     * @return KontragentsView1_2
     */
    public ViewObjectImpl getKontragentsView1_2() {
        return (ViewObjectImpl) findViewObject("KontragentsView1_2");
    }

    /**
     * Container's getter for OrdersView1_6.
     * @return OrdersView1_6
     */
    public ViewObjectImpl getOrdersView1_6() {
        return (ViewObjectImpl) findViewObject("OrdersView1_6");
    }

    /**
     * Container's getter for NomenklaturaView1_2.
     * @return NomenklaturaView1_2
     */
    public ViewObjectImpl getNomenklaturaView1_2() {
        return (ViewObjectImpl) findViewObject("NomenklaturaView1_2");
    }

    /**
     * Container's getter for UserSettingsView1_6.
     * @return UserSettingsView1_6
     */
    public ViewObjectImpl getUserSettingsView1_6() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_6");
    }

    /**
     * Container's getter for OrdersView1_7.
     * @return OrdersView1_7
     */
    public ViewObjectImpl getOrdersView1_7() {
        return (ViewObjectImpl) findViewObject("OrdersView1_7");
    }

    /**
     * Container's getter for EntrySettingsView1_2.
     * @return EntrySettingsView1_2
     */
    public ViewObjectImpl getEntrySettingsView1_2() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView1_2");
    }

    /**
     * Container's getter for EntrySettingsView1_3.
     * @return EntrySettingsView1_3
     */
    public ViewObjectImpl getEntrySettingsView1_3() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView1_3");
    }

    /**
     * Container's getter for MovesView1_4.
     * @return MovesView1_4
     */
    public ViewObjectImpl getMovesView1_4() {
        return (ViewObjectImpl) findViewObject("MovesView1_4");
    }

    /**
     * Container's getter for MovesView1_5.
     * @return MovesView1_5
     */
    public ViewObjectImpl getMovesView1_5() {
        return (ViewObjectImpl) findViewObject("MovesView1_5");
    }

    /**
     * Container's getter for PlanAccView1_3.
     * @return PlanAccView1_3
     */
    public ViewObjectImpl getPlanAccView1_3() {
        return (ViewObjectImpl) findViewObject("PlanAccView1_3");
    }

    /**
     * Container's getter for PlanAccSubcontoView1_2.
     * @return PlanAccSubcontoView1_2
     */
    public ViewObjectImpl getPlanAccSubcontoView1_2() {
        return (ViewObjectImpl) findViewObject("PlanAccSubcontoView1_2");
    }

    /**
     * Container's getter for PlanAccSubcontoView1_3.
     * @return PlanAccSubcontoView1_3
     */
    public ViewObjectImpl getPlanAccSubcontoView1_3() {
        return (ViewObjectImpl) findViewObject("PlanAccSubcontoView1_3");
    }

    /**
     * Container's getter for EntrySettingsView1_4.
     * @return EntrySettingsView1_4
     */
    public ViewObjectImpl getEntrySettingsView1_4() {
        return (ViewObjectImpl) findViewObject("EntrySettingsView1_4");
    }

    /**
     * Container's getter for MovesView1_6.
     * @return MovesView1_6
     */
    public ViewObjectImpl getMovesView1_6() {
        return (ViewObjectImpl) findViewObject("MovesView1_6");
    }

    /**
     * Container's getter for NumeratorView1_2.
     * @return NumeratorView1_2
     */
    public ViewObjectImpl getNumeratorView1_2() {
        return (ViewObjectImpl) findViewObject("NumeratorView1_2");
    }

    /**
     * Container's getter for PlanTypeSubcontoView1_2.
     * @return PlanTypeSubcontoView1_2
     */
    public ViewObjectImpl getPlanTypeSubcontoView1_2() {
        return (ViewObjectImpl) findViewObject("PlanTypeSubcontoView1_2");
    }

    /**
     * Container's getter for MovesView1_7.
     * @return MovesView1_7
     */
    public ViewObjectImpl getMovesView1_7() {
        return (ViewObjectImpl) findViewObject("MovesView1_7");
    }

    /**
     * Container's getter for OrdersView1_8.
     * @return OrdersView1_8
     */
    public ViewObjectImpl getOrdersView1_8() {
        return (ViewObjectImpl) findViewObject("OrdersView1_8");
    }

    /**
     * Container's getter for UserSettingsView1_7.
     * @return UserSettingsView1_7
     */
    public ViewObjectImpl getUserSettingsView1_7() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_7");
    }

    /**
     * Container's getter for OrdersView1_9.
     * @return OrdersView1_9
     */
    public ViewObjectImpl getOrdersView1_9() {
        return (ViewObjectImpl) findViewObject("OrdersView1_9");
    }

    /**
     * Container's getter for UsersGroupsView1_3.
     * @return UsersGroupsView1_3
     */
    public ViewObjectImpl getUsersGroupsView1_3() {
        return (ViewObjectImpl) findViewObject("UsersGroupsView1_3");
    }

    /**
     * Container's getter for UserSettingsView1_8.
     * @return UserSettingsView1_8
     */
    public ViewObjectImpl getUserSettingsView1_8() {
        return (ViewObjectImpl) findViewObject("UserSettingsView1_8");
    }

    /**
     * Container's getter for ZatratyView1_2.
     * @return ZatratyView1_2
     */
    public ViewObjectImpl getZatratyView1_2() {
        return (ViewObjectImpl) findViewObject("ZatratyView1_2");
    }

    /**
     * Container's getter for KontragentsItemsLookupVO1.
     * @return KontragentsItemsLookupVO1
     */
    public KontragentsItemsLookupVOImpl getKontragentsItemsLookupVO1() {
        return (KontragentsItemsLookupVOImpl) findViewObject("KontragentsItemsLookupVO1");
    }

    /**
     * Container's getter for KontragentsINNLookupVO1.
     * @return KontragentsINNLookupVO1
     */
    public ViewObjectImpl getKontragentsINNLookupVO1() {
        return (ViewObjectImpl) findViewObject("KontragentsINNLookupVO1");
    }

    /**
     * Container's getter for CallLogFk1Link1.
     * @return CallLogFk1Link1
     */
    public ViewLinkImpl getCallLogFk1Link1() {
        return (ViewLinkImpl) findViewLink("CallLogFk1Link1");
    }

    /**
     * Container's getter for CallLogFk3Link1.
     * @return CallLogFk3Link1
     */
    public ViewLinkImpl getCallLogFk3Link1() {
        return (ViewLinkImpl) findViewLink("CallLogFk3Link1");
    }

    /**
     * Container's getter for CompaignsDetailsFk1Link1.
     * @return CompaignsDetailsFk1Link1
     */
    public ViewLinkImpl getCompaignsDetailsFk1Link1() {
        return (ViewLinkImpl) findViewLink("CompaignsDetailsFk1Link1");
    }

    /**
     * Container's getter for CallLogFk2Link1.
     * @return CallLogFk2Link1
     */
    public ViewLinkImpl getCallLogFk2Link1() {
        return (ViewLinkImpl) findViewLink("CallLogFk2Link1");
    }

    /**
     * Container's getter for CompaignsDetailsFk3Link1.
     * @return CompaignsDetailsFk3Link1
     */
    public ViewLinkImpl getCompaignsDetailsFk3Link1() {
        return (ViewLinkImpl) findViewLink("CompaignsDetailsFk3Link1");
    }

    /**
     * Container's getter for DivisionsDivisionsFk1Link1.
     * @return DivisionsDivisionsFk1Link1
     */
    public ViewLinkImpl getDivisionsDivisionsFk1Link1() {
        return (ViewLinkImpl) findViewLink("DivisionsDivisionsFk1Link1");
    }

    /**
     * Container's getter for ExRatesSettingsCurrencFk1Link1.
     * @return ExRatesSettingsCurrencFk1Link1
     */
    public ViewLinkImpl getExRatesSettingsCurrencFk1Link1() {
        return (ViewLinkImpl) findViewLink("ExRatesSettingsCurrencFk1Link1");
    }

    /**
     * Container's getter for KassaKassaFk1Link1.
     * @return KassaKassaFk1Link1
     */
    public ViewLinkImpl getKassaKassaFk1Link1() {
        return (ViewLinkImpl) findViewLink("KassaKassaFk1Link1");
    }

    /**
     * Container's getter for KassaCurrencyFk1Link1.
     * @return KassaCurrencyFk1Link1
     */
    public ViewLinkImpl getKassaCurrencyFk1Link1() {
        return (ViewLinkImpl) findViewLink("KassaCurrencyFk1Link1");
    }

    /**
     * Container's getter for KassaDivisionsFk1Link1.
     * @return KassaDivisionsFk1Link1
     */
    public ViewLinkImpl getKassaDivisionsFk1Link1() {
        return (ViewLinkImpl) findViewLink("KassaDivisionsFk1Link1");
    }

    /**
     * Container's getter for KassaFirmsFk1Link1.
     * @return KassaFirmsFk1Link1
     */
    public ViewLinkImpl getKassaFirmsFk1Link1() {
        return (ViewLinkImpl) findViewLink("KassaFirmsFk1Link1");
    }

    /**
     * Container's getter for KontragentsKontragentsFk1Link1.
     * @return KontragentsKontragentsFk1Link1
     */
    public ViewLinkImpl getKontragentsKontragentsFk1Link1() {
        return (ViewLinkImpl) findViewLink("KontragentsKontragentsFk1Link1");
    }

    /**
     * Container's getter for CompaignsDetailsFk2Link1.
     * @return CompaignsDetailsFk2Link1
     */
    public ViewLinkImpl getCompaignsDetailsFk2Link1() {
        return (ViewLinkImpl) findViewLink("CompaignsDetailsFk2Link1");
    }

    /**
     * Container's getter for ContactDetailsFk1Link1.
     * @return ContactDetailsFk1Link1
     */
    public ViewLinkImpl getContactDetailsFk1Link1() {
        return (ViewLinkImpl) findViewLink("ContactDetailsFk1Link1");
    }

    /**
     * Container's getter for MovesCurrencyFk1Link1.
     * @return MovesCurrencyFk1Link1
     */
    public ViewLinkImpl getMovesCurrencyFk1Link1() {
        return (ViewLinkImpl) findViewLink("MovesCurrencyFk1Link1");
    }

    /**
     * Container's getter for MovesCurrencyFk2Link1.
     * @return MovesCurrencyFk2Link1
     */
    public ViewLinkImpl getMovesCurrencyFk2Link1() {
        return (ViewLinkImpl) findViewLink("MovesCurrencyFk2Link1");
    }

    /**
     * Container's getter for NomenklaturaNomenklaturaFk1Link1.
     * @return NomenklaturaNomenklaturaFk1Link1
     */
    public ViewLinkImpl getNomenklaturaNomenklaturaFk1Link1() {
        return (ViewLinkImpl) findViewLink("NomenklaturaNomenklaturaFk1Link1");
    }

    /**
     * Container's getter for OrdersCurrencyFk1Link1.
     * @return OrdersCurrencyFk1Link1
     */
    public ViewLinkImpl getOrdersCurrencyFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersCurrencyFk1Link1");
    }

    /**
     * Container's getter for OrdersDivisionsFk1Link1.
     * @return OrdersDivisionsFk1Link1
     */
    public ViewLinkImpl getOrdersDivisionsFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersDivisionsFk1Link1");
    }

    /**
     * Container's getter for OrdersFirmsFk1Link1.
     * @return OrdersFirmsFk1Link1
     */
    public ViewLinkImpl getOrdersFirmsFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersFirmsFk1Link1");
    }

    /**
     * Container's getter for OrdersKassaFk1Link1.
     * @return OrdersKassaFk1Link1
     */
    public ViewLinkImpl getOrdersKassaFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersKassaFk1Link1");
    }

    /**
     * Container's getter for OrdersKontragentsFk1Link1.
     * @return OrdersKontragentsFk1Link1
     */
    public ViewLinkImpl getOrdersKontragentsFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersKontragentsFk1Link1");
    }

    /**
     * Container's getter for OrdersStatusFkLink1.
     * @return OrdersStatusFkLink1
     */
    public ViewLinkImpl getOrdersStatusFkLink1() {
        return (ViewLinkImpl) findViewLink("OrdersStatusFkLink1");
    }

    /**
     * Container's getter for PlanAccFk1Link1.
     * @return PlanAccFk1Link1
     */
    public ViewLinkImpl getPlanAccFk1Link1() {
        return (ViewLinkImpl) findViewLink("PlanAccFk1Link1");
    }

    /**
     * Container's getter for MovesPlanAccFk2Link1.
     * @return MovesPlanAccFk2Link1
     */
    public ViewLinkImpl getMovesPlanAccFk2Link1() {
        return (ViewLinkImpl) findViewLink("MovesPlanAccFk2Link1");
    }

    /**
     * Container's getter for MovesPlanAccFk1Link1.
     * @return MovesPlanAccFk1Link1
     */
    public ViewLinkImpl getMovesPlanAccFk1Link1() {
        return (ViewLinkImpl) findViewLink("MovesPlanAccFk1Link1");
    }

    /**
     * Container's getter for EntrySettingsPlanAccKredLink1.
     * @return EntrySettingsPlanAccKredLink1
     */
    public ViewLinkImpl getEntrySettingsPlanAccKredLink1() {
        return (ViewLinkImpl) findViewLink("EntrySettingsPlanAccKredLink1");
    }

    /**
     * Container's getter for EntrySettingsPlanAccDebLink1.
     * @return EntrySettingsPlanAccDebLink1
     */
    public ViewLinkImpl getEntrySettingsPlanAccDebLink1() {
        return (ViewLinkImpl) findViewLink("EntrySettingsPlanAccDebLink1");
    }

    /**
     * Container's getter for PlanAccFk2Link1.
     * @return PlanAccFk2Link1
     */
    public ViewLinkImpl getPlanAccFk2Link1() {
        return (ViewLinkImpl) findViewLink("PlanAccFk2Link1");
    }

    /**
     * Container's getter for PlanAccSubcontoFk1Link1.
     * @return PlanAccSubcontoFk1Link1
     */
    public ViewLinkImpl getPlanAccSubcontoFk1Link1() {
        return (ViewLinkImpl) findViewLink("PlanAccSubcontoFk1Link1");
    }

    /**
     * Container's getter for PlanAccSubcontoFk2Link1.
     * @return PlanAccSubcontoFk2Link1
     */
    public ViewLinkImpl getPlanAccSubcontoFk2Link1() {
        return (ViewLinkImpl) findViewLink("PlanAccSubcontoFk2Link1");
    }

    /**
     * Container's getter for RegRatesFk1Link1.
     * @return RegRatesFk1Link1
     */
    public ViewLinkImpl getRegRatesFk1Link1() {
        return (ViewLinkImpl) findViewLink("RegRatesFk1Link1");
    }

    /**
     * Container's getter for MovesTypeDefFk1Link1.
     * @return MovesTypeDefFk1Link1
     */
    public ViewLinkImpl getMovesTypeDefFk1Link1() {
        return (ViewLinkImpl) findViewLink("MovesTypeDefFk1Link1");
    }

    /**
     * Container's getter for PlanTypeSubcontoTypeDFk1Link1.
     * @return PlanTypeSubcontoTypeDFk1Link1
     */
    public ViewLinkImpl getPlanTypeSubcontoTypeDFk1Link1() {
        return (ViewLinkImpl) findViewLink("PlanTypeSubcontoTypeDFk1Link1");
    }

    /**
     * Container's getter for NumeratorTypeDefFk1Link1.
     * @return NumeratorTypeDefFk1Link1
     */
    public ViewLinkImpl getNumeratorTypeDefFk1Link1() {
        return (ViewLinkImpl) findViewLink("NumeratorTypeDefFk1Link1");
    }

    /**
     * Container's getter for EntrySettingsTypeDefFk1Link1.
     * @return EntrySettingsTypeDefFk1Link1
     */
    public ViewLinkImpl getEntrySettingsTypeDefFk1Link1() {
        return (ViewLinkImpl) findViewLink("EntrySettingsTypeDefFk1Link1");
    }

    /**
     * Container's getter for MovesFk1Link1.
     * @return MovesFk1Link1
     */
    public ViewLinkImpl getMovesFk1Link1() {
        return (ViewLinkImpl) findViewLink("MovesFk1Link1");
    }

    /**
     * Container's getter for OrdersFk1Link1.
     * @return OrdersFk1Link1
     */
    public ViewLinkImpl getOrdersFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersFk1Link1");
    }

    /**
     * Container's getter for OrdersUsersFk1Link1.
     * @return OrdersUsersFk1Link1
     */
    public ViewLinkImpl getOrdersUsersFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersUsersFk1Link1");
    }

    /**
     * Container's getter for UsersGroupsFk1Link1.
     * @return UsersGroupsFk1Link1
     */
    public ViewLinkImpl getUsersGroupsFk1Link1() {
        return (ViewLinkImpl) findViewLink("UsersGroupsFk1Link1");
    }

    /**
     * Container's getter for UsersGroupsFk2Link1.
     * @return UsersGroupsFk2Link1
     */
    public ViewLinkImpl getUsersGroupsFk2Link1() {
        return (ViewLinkImpl) findViewLink("UsersGroupsFk2Link1");
    }

    /**
     * Container's getter for UserSettingsCurrencyFk1Link1.
     * @return UserSettingsCurrencyFk1Link1
     */
    public ViewLinkImpl getUserSettingsCurrencyFk1Link1() {
        return (ViewLinkImpl) findViewLink("UserSettingsCurrencyFk1Link1");
    }

    /**
     * Container's getter for UserSettingsDivisionsFk1Link1.
     * @return UserSettingsDivisionsFk1Link1
     */
    public ViewLinkImpl getUserSettingsDivisionsFk1Link1() {
        return (ViewLinkImpl) findViewLink("UserSettingsDivisionsFk1Link1");
    }

    /**
     * Container's getter for UserSettingsFirmsFk1Link1.
     * @return UserSettingsFirmsFk1Link1
     */
    public ViewLinkImpl getUserSettingsFirmsFk1Link1() {
        return (ViewLinkImpl) findViewLink("UserSettingsFirmsFk1Link1");
    }

    /**
     * Container's getter for UserSettingsFk1Link1.
     * @return UserSettingsFk1Link1
     */
    public ViewLinkImpl getUserSettingsFk1Link1() {
        return (ViewLinkImpl) findViewLink("UserSettingsFk1Link1");
    }

    /**
     * Container's getter for UserSettingsKassaFk1Link1.
     * @return UserSettingsKassaFk1Link1
     */
    public ViewLinkImpl getUserSettingsKassaFk1Link1() {
        return (ViewLinkImpl) findViewLink("UserSettingsKassaFk1Link1");
    }

    /**
     * Container's getter for UserSettingsNomenklaturFk1Link1.
     * @return UserSettingsNomenklaturFk1Link1
     */
    public ViewLinkImpl getUserSettingsNomenklaturFk1Link1() {
        return (ViewLinkImpl) findViewLink("UserSettingsNomenklaturFk1Link1");
    }

    /**
     * Container's getter for UserSettingsUsersFk1Link1.
     * @return UserSettingsUsersFk1Link1
     */
    public ViewLinkImpl getUserSettingsUsersFk1Link1() {
        return (ViewLinkImpl) findViewLink("UserSettingsUsersFk1Link1");
    }

    /**
     * Container's getter for ZatratyZatratyFk1Link1.
     * @return ZatratyZatratyFk1Link1
     */
    public ViewLinkImpl getZatratyZatratyFk1Link1() {
        return (ViewLinkImpl) findViewLink("ZatratyZatratyFk1Link1");
    }

    /**
     * Container's getter for CallLogFk1Link2.
     * @return CallLogFk1Link2
     */
    public ViewLinkImpl getCallLogFk1Link2() {
        return (ViewLinkImpl) findViewLink("CallLogFk1Link2");
    }

    /**
     * Container's getter for CompaignsDetailsFk1Link2.
     * @return CompaignsDetailsFk1Link2
     */
    public ViewLinkImpl getCompaignsDetailsFk1Link2() {
        return (ViewLinkImpl) findViewLink("CompaignsDetailsFk1Link2");
    }

    /**
     * Container's getter for CallLogFk3Link2.
     * @return CallLogFk3Link2
     */
    public ViewLinkImpl getCallLogFk3Link2() {
        return (ViewLinkImpl) findViewLink("CallLogFk3Link2");
    }

    /**
     * Container's getter for CallLogFk2Link2.
     * @return CallLogFk2Link2
     */
    public ViewLinkImpl getCallLogFk2Link2() {
        return (ViewLinkImpl) findViewLink("CallLogFk2Link2");
    }

    /**
     * Container's getter for CompaignsDetailsFk3Link2.
     * @return CompaignsDetailsFk3Link2
     */
    public ViewLinkImpl getCompaignsDetailsFk3Link2() {
        return (ViewLinkImpl) findViewLink("CompaignsDetailsFk3Link2");
    }

    /**
     * Container's getter for ExRatesSettingsCurrencFk1Link2.
     * @return ExRatesSettingsCurrencFk1Link2
     */
    public ViewLinkImpl getExRatesSettingsCurrencFk1Link2() {
        return (ViewLinkImpl) findViewLink("ExRatesSettingsCurrencFk1Link2");
    }

    /**
     * Container's getter for KassaCurrencyFk1Link2.
     * @return KassaCurrencyFk1Link2
     */
    public ViewLinkImpl getKassaCurrencyFk1Link2() {
        return (ViewLinkImpl) findViewLink("KassaCurrencyFk1Link2");
    }

    /**
     * Container's getter for MovesCurrencyFk1Link2.
     * @return MovesCurrencyFk1Link2
     */
    public ViewLinkImpl getMovesCurrencyFk1Link2() {
        return (ViewLinkImpl) findViewLink("MovesCurrencyFk1Link2");
    }

    /**
     * Container's getter for MovesCurrencyFk2Link2.
     * @return MovesCurrencyFk2Link2
     */
    public ViewLinkImpl getMovesCurrencyFk2Link2() {
        return (ViewLinkImpl) findViewLink("MovesCurrencyFk2Link2");
    }

    /**
     * Container's getter for OrdersCurrencyFk1Link2.
     * @return OrdersCurrencyFk1Link2
     */
    public ViewLinkImpl getOrdersCurrencyFk1Link2() {
        return (ViewLinkImpl) findViewLink("OrdersCurrencyFk1Link2");
    }

    /**
     * Container's getter for RegRatesFk1Link2.
     * @return RegRatesFk1Link2
     */
    public ViewLinkImpl getRegRatesFk1Link2() {
        return (ViewLinkImpl) findViewLink("RegRatesFk1Link2");
    }

    /**
     * Container's getter for UserSettingsCurrencyFk1Link2.
     * @return UserSettingsCurrencyFk1Link2
     */
    public ViewLinkImpl getUserSettingsCurrencyFk1Link2() {
        return (ViewLinkImpl) findViewLink("UserSettingsCurrencyFk1Link2");
    }

    /**
     * Container's getter for DivisionsDivisionsFk1Link2.
     * @return DivisionsDivisionsFk1Link2
     */
    public ViewLinkImpl getDivisionsDivisionsFk1Link2() {
        return (ViewLinkImpl) findViewLink("DivisionsDivisionsFk1Link2");
    }

    /**
     * Container's getter for KassaDivisionsFk1Link2.
     * @return KassaDivisionsFk1Link2
     */
    public ViewLinkImpl getKassaDivisionsFk1Link2() {
        return (ViewLinkImpl) findViewLink("KassaDivisionsFk1Link2");
    }

    /**
     * Container's getter for OrdersDivisionsFk1Link2.
     * @return OrdersDivisionsFk1Link2
     */
    public ViewLinkImpl getOrdersDivisionsFk1Link2() {
        return (ViewLinkImpl) findViewLink("OrdersDivisionsFk1Link2");
    }

    /**
     * Container's getter for UserSettingsDivisionsFk1Link2.
     * @return UserSettingsDivisionsFk1Link2
     */
    public ViewLinkImpl getUserSettingsDivisionsFk1Link2() {
        return (ViewLinkImpl) findViewLink("UserSettingsDivisionsFk1Link2");
    }

    /**
     * Container's getter for PlanAccFk2Link2.
     * @return PlanAccFk2Link2
     */
    public ViewLinkImpl getPlanAccFk2Link2() {
        return (ViewLinkImpl) findViewLink("PlanAccFk2Link2");
    }

    /**
     * Container's getter for KassaFirmsFk1Link2.
     * @return KassaFirmsFk1Link2
     */
    public ViewLinkImpl getKassaFirmsFk1Link2() {
        return (ViewLinkImpl) findViewLink("KassaFirmsFk1Link2");
    }

    /**
     * Container's getter for OrdersFirmsFk1Link2.
     * @return OrdersFirmsFk1Link2
     */
    public ViewLinkImpl getOrdersFirmsFk1Link2() {
        return (ViewLinkImpl) findViewLink("OrdersFirmsFk1Link2");
    }

    /**
     * Container's getter for UserSettingsFirmsFk1Link2.
     * @return UserSettingsFirmsFk1Link2
     */
    public ViewLinkImpl getUserSettingsFirmsFk1Link2() {
        return (ViewLinkImpl) findViewLink("UserSettingsFirmsFk1Link2");
    }

    /**
     * Container's getter for UsersGroupsFk1Link2.
     * @return UsersGroupsFk1Link2
     */
    public ViewLinkImpl getUsersGroupsFk1Link2() {
        return (ViewLinkImpl) findViewLink("UsersGroupsFk1Link2");
    }

    /**
     * Container's getter for KassaKassaFk1Link2.
     * @return KassaKassaFk1Link2
     */
    public ViewLinkImpl getKassaKassaFk1Link2() {
        return (ViewLinkImpl) findViewLink("KassaKassaFk1Link2");
    }

    /**
     * Container's getter for OrdersKassaFk1Link2.
     * @return OrdersKassaFk1Link2
     */
    public ViewLinkImpl getOrdersKassaFk1Link2() {
        return (ViewLinkImpl) findViewLink("OrdersKassaFk1Link2");
    }

    /**
     * Container's getter for UserSettingsKassaFk1Link2.
     * @return UserSettingsKassaFk1Link2
     */
    public ViewLinkImpl getUserSettingsKassaFk1Link2() {
        return (ViewLinkImpl) findViewLink("UserSettingsKassaFk1Link2");
    }

    /**
     * Container's getter for CompaignsDetailsFk2Link2.
     * @return CompaignsDetailsFk2Link2
     */
    public ViewLinkImpl getCompaignsDetailsFk2Link2() {
        return (ViewLinkImpl) findViewLink("CompaignsDetailsFk2Link2");
    }

    /**
     * Container's getter for ContactDetailsFk1Link2.
     * @return ContactDetailsFk1Link2
     */
    public ViewLinkImpl getContactDetailsFk1Link2() {
        return (ViewLinkImpl) findViewLink("ContactDetailsFk1Link2");
    }

    /**
     * Container's getter for KontragentsKontragentsFk1Link2.
     * @return KontragentsKontragentsFk1Link2
     */
    public ViewLinkImpl getKontragentsKontragentsFk1Link2() {
        return (ViewLinkImpl) findViewLink("KontragentsKontragentsFk1Link2");
    }

    /**
     * Container's getter for OrdersKontragentsFk1Link2.
     * @return OrdersKontragentsFk1Link2
     */
    public ViewLinkImpl getOrdersKontragentsFk1Link2() {
        return (ViewLinkImpl) findViewLink("OrdersKontragentsFk1Link2");
    }

    /**
     * Container's getter for NomenklaturaNomenklaturaFk1Link2.
     * @return NomenklaturaNomenklaturaFk1Link2
     */
    public ViewLinkImpl getNomenklaturaNomenklaturaFk1Link2() {
        return (ViewLinkImpl) findViewLink("NomenklaturaNomenklaturaFk1Link2");
    }

    /**
     * Container's getter for UserSettingsNomenklaturFk1Link2.
     * @return UserSettingsNomenklaturFk1Link2
     */
    public ViewLinkImpl getUserSettingsNomenklaturFk1Link2() {
        return (ViewLinkImpl) findViewLink("UserSettingsNomenklaturFk1Link2");
    }

    /**
     * Container's getter for OrdersStatusFkLink2.
     * @return OrdersStatusFkLink2
     */
    public ViewLinkImpl getOrdersStatusFkLink2() {
        return (ViewLinkImpl) findViewLink("OrdersStatusFkLink2");
    }

    /**
     * Container's getter for EntrySettingsPlanAccDebLink2.
     * @return EntrySettingsPlanAccDebLink2
     */
    public ViewLinkImpl getEntrySettingsPlanAccDebLink2() {
        return (ViewLinkImpl) findViewLink("EntrySettingsPlanAccDebLink2");
    }

    /**
     * Container's getter for EntrySettingsPlanAccKredLink2.
     * @return EntrySettingsPlanAccKredLink2
     */
    public ViewLinkImpl getEntrySettingsPlanAccKredLink2() {
        return (ViewLinkImpl) findViewLink("EntrySettingsPlanAccKredLink2");
    }

    /**
     * Container's getter for MovesPlanAccFk1Link2.
     * @return MovesPlanAccFk1Link2
     */
    public ViewLinkImpl getMovesPlanAccFk1Link2() {
        return (ViewLinkImpl) findViewLink("MovesPlanAccFk1Link2");
    }

    /**
     * Container's getter for MovesPlanAccFk2Link2.
     * @return MovesPlanAccFk2Link2
     */
    public ViewLinkImpl getMovesPlanAccFk2Link2() {
        return (ViewLinkImpl) findViewLink("MovesPlanAccFk2Link2");
    }

    /**
     * Container's getter for PlanAccFk1Link2.
     * @return PlanAccFk1Link2
     */
    public ViewLinkImpl getPlanAccFk1Link2() {
        return (ViewLinkImpl) findViewLink("PlanAccFk1Link2");
    }

    /**
     * Container's getter for PlanAccSubcontoFk1Link2.
     * @return PlanAccSubcontoFk1Link2
     */
    public ViewLinkImpl getPlanAccSubcontoFk1Link2() {
        return (ViewLinkImpl) findViewLink("PlanAccSubcontoFk1Link2");
    }

    /**
     * Container's getter for PlanAccSubcontoFk2Link2.
     * @return PlanAccSubcontoFk2Link2
     */
    public ViewLinkImpl getPlanAccSubcontoFk2Link2() {
        return (ViewLinkImpl) findViewLink("PlanAccSubcontoFk2Link2");
    }

    /**
     * Container's getter for EntrySettingsTypeDefFk1Link2.
     * @return EntrySettingsTypeDefFk1Link2
     */
    public ViewLinkImpl getEntrySettingsTypeDefFk1Link2() {
        return (ViewLinkImpl) findViewLink("EntrySettingsTypeDefFk1Link2");
    }

    /**
     * Container's getter for MovesTypeDefFk1Link2.
     * @return MovesTypeDefFk1Link2
     */
    public ViewLinkImpl getMovesTypeDefFk1Link2() {
        return (ViewLinkImpl) findViewLink("MovesTypeDefFk1Link2");
    }

    /**
     * Container's getter for NumeratorTypeDefFk1Link2.
     * @return NumeratorTypeDefFk1Link2
     */
    public ViewLinkImpl getNumeratorTypeDefFk1Link2() {
        return (ViewLinkImpl) findViewLink("NumeratorTypeDefFk1Link2");
    }

    /**
     * Container's getter for PlanTypeSubcontoTypeDFk1Link2.
     * @return PlanTypeSubcontoTypeDFk1Link2
     */
    public ViewLinkImpl getPlanTypeSubcontoTypeDFk1Link2() {
        return (ViewLinkImpl) findViewLink("PlanTypeSubcontoTypeDFk1Link2");
    }

    /**
     * Container's getter for MovesFk1Link2.
     * @return MovesFk1Link2
     */
    public ViewLinkImpl getMovesFk1Link2() {
        return (ViewLinkImpl) findViewLink("MovesFk1Link2");
    }

    /**
     * Container's getter for OrdersFk1Link2.
     * @return OrdersFk1Link2
     */
    public ViewLinkImpl getOrdersFk1Link2() {
        return (ViewLinkImpl) findViewLink("OrdersFk1Link2");
    }

    /**
     * Container's getter for UserSettingsFk1Link2.
     * @return UserSettingsFk1Link2
     */
    public ViewLinkImpl getUserSettingsFk1Link2() {
        return (ViewLinkImpl) findViewLink("UserSettingsFk1Link2");
    }

    /**
     * Container's getter for OrdersUsersFk1Link2.
     * @return OrdersUsersFk1Link2
     */
    public ViewLinkImpl getOrdersUsersFk1Link2() {
        return (ViewLinkImpl) findViewLink("OrdersUsersFk1Link2");
    }

    /**
     * Container's getter for UsersGroupsFk2Link2.
     * @return UsersGroupsFk2Link2
     */
    public ViewLinkImpl getUsersGroupsFk2Link2() {
        return (ViewLinkImpl) findViewLink("UsersGroupsFk2Link2");
    }

    /**
     * Container's getter for UserSettingsUsersFk1Link2.
     * @return UserSettingsUsersFk1Link2
     */
    public ViewLinkImpl getUserSettingsUsersFk1Link2() {
        return (ViewLinkImpl) findViewLink("UserSettingsUsersFk1Link2");
    }

    /**
     * Container's getter for ZatratyZatratyFk1Link2.
     * @return ZatratyZatratyFk1Link2
     */
    public ViewLinkImpl getZatratyZatratyFk1Link2() {
        return (ViewLinkImpl) findViewLink("ZatratyZatratyFk1Link2");
    }

    @Override
    protected void prepareSession(Session session) {
        // TODO Implement this method
        super.prepareSession(session);
        this.getDBTransaction().setClearCacheOnRollback(false);
    }

    /**
     * Container's getter for KontragentsView3.
     * @return KontragentsView3
     */
    public KontragentsViewImpl getKontragentsView3() {
        return (KontragentsViewImpl) findViewObject("KontragentsView3");
    }

    /**
     * Container's getter for ContactDetailsView3.
     * @return ContactDetailsView3
     */
    public ContactDetailsViewImpl getContactDetailsView3() {
        return (ContactDetailsViewImpl) findViewObject("ContactDetailsView3");
    }

    /**
     * Container's getter for CompaignsDetailsKontragFnLink.
     * @return CompaignsDetailsKontragFnLink
     */
    public ViewLinkImpl getCompaignsDetailsKontragFnLink() {
        return (ViewLinkImpl) findViewLink("CompaignsDetailsKontragFnLink");
    }

    /**
     * Container's getter for VwCompDetails1.
     * @return VwCompDetails1
     */
    public ViewObjectImpl getVwCompDetails1() {
        return (ViewObjectImpl) findViewObject("VwCompDetails1");
    }


    /**
     * Container's getter for VwCompDetails2.
     * @return VwCompDetails2
     */
    public ViewObjectImpl getVwCompDetails2() {
        return (ViewObjectImpl) findViewObject("VwCompDetails2");
    }

    /**
     * Container's getter for VwCompDetailsFkLink1.
     * @return VwCompDetailsFkLink1
     */
    public ViewLinkImpl getVwCompDetailsFkLink1() {
        return (ViewLinkImpl) findViewLink("VwCompDetailsFkLink1");
    }


    /**
     * Container's getter for DivisionsRootView2.
     * @return DivisionsRootView2
     */
    public ViewObjectImpl getDivisionsRootView2() {
        return (ViewObjectImpl) findViewObject("DivisionsRootView2");
    }

    /**
     * Container's getter for DivisionsView3.
     * @return DivisionsView3
     */
    public DivisionsViewImpl getDivisionsView3() {
        return (DivisionsViewImpl) findViewObject("DivisionsView3");
    }

    /**
     * Container's getter for DivRootDivisionsFkLink.
     * @return DivRootDivisionsFkLink
     */
    public ViewLinkImpl getDivRootDivisionsFkLink() {
        return (ViewLinkImpl) findViewLink("DivRootDivisionsFkLink");
    }
    
    public void deleteChildren(RowIterator ri, Key selectedNodeKey) {
            if (ri != null && selectedNodeKey != null) {

                Row last = ri.last();
                Key lastRowKey = last.getKey();
                // if the select row is not the last row in the row iterator...

                Row[] rows = ri.findByKey(selectedNodeKey, 1);
                if (rows != null) {

                    for (Row row : rows) {
                        row.remove();
                        //this.getTransaction().commit();
                    }

                } else {
                    System.out.println("Node not Found for " + selectedNodeKey);
                }


            }
        }


    /**
     * Container's getter for GroupmembersView2.
     * @return GroupmembersView2
     */
    public GroupmembersViewImpl getGroupmembersView2() {
        return (GroupmembersViewImpl) findViewObject("GroupmembersView2");
    }


    /**
     * Container's getter for GroupmembersView3.
     * @return GroupmembersView3
     */
    public GroupmembersViewImpl getGroupmembersView3() {
        return (GroupmembersViewImpl) findViewObject("GroupmembersView3");
    }

    /**
     * Container's getter for GroupmembersFk2Link1.
     * @return GroupmembersFk2Link1
     */
    public ViewLinkImpl getGroupmembersFk2Link1() {
        return (ViewLinkImpl) findViewLink("GroupmembersFk2Link1");
    }


    /**
     * Container's getter for GroupmembersView5.
     * @return GroupmembersView5
     */
    public GroupmembersViewImpl getGroupmembersView5() {
        return (GroupmembersViewImpl) findViewObject("GroupmembersView5");
    }

    /**
     * Container's getter for GroupmembersFkUsersLink1.
     * @return GroupmembersFkUsersLink1
     */
    public ViewLinkImpl getGroupmembersFkUsersLink1() {
        return (ViewLinkImpl) findViewLink("GroupmembersFkUsersLink1");
    }


    /**
     * Container's getter for DivisionSotrView3.
     * @return DivisionSotrView3
     */
    public ViewObjectImpl getDivisionSotrView3() {
        return (ViewObjectImpl) findViewObject("DivisionSotrView3");
    }


    /**
     * Container's getter for DivisionSotrView1.
     * @return DivisionSotrView1
     */
    public ViewObjectImpl getDivisionSotrView1() {
        return (ViewObjectImpl) findViewObject("DivisionSotrView1");
    }

    /**
     * Container's getter for DivisionSotrFk2Link1.
     * @return DivisionSotrFk2Link1
     */
    public ViewLinkImpl getDivisionSotrFk2Link1() {
        return (ViewLinkImpl) findViewLink("DivisionSotrFk2Link1");
    }

    /**
     * Container's getter for DivisionSotrView2.
     * @return DivisionSotrView2
     */
    public ViewObjectImpl getDivisionSotrView2() {
        return (ViewObjectImpl) findViewObject("DivisionSotrView2");
    }

    /**
     * Container's getter for DivisionSotrFk1Link1.
     * @return DivisionSotrFk1Link1
     */
    public ViewLinkImpl getDivisionSotrFk1Link1() {
        return (ViewLinkImpl) findViewLink("DivisionSotrFk1Link1");
    }

    /**
     * Container's getter for KassaVO1.
     * @return KassaVO1
     */
    public KassaVOImpl getKassaVO1() {
        return (KassaVOImpl) findViewObject("KassaVO1");
    }

    /**
     * Container's getter for UsersItemsLookupVO1.
     * @return UsersItemsLookupVO1
     */
    public UsersItemsLookupVOImpl getUsersItemsLookupVO1() {
        return (UsersItemsLookupVOImpl) findViewObject("UsersItemsLookupVO1");
    }

    /**
     * Container's getter for OrdersTpUslugiView1.
     * @return OrdersTpUslugiView1
     */
    public ViewObjectImpl getOrdersTpUslugiView1() {
        return (ViewObjectImpl) findViewObject("OrdersTpUslugiView1");
    }

    /**
     * Container's getter for OrdersTpUslugiView2.
     * @return OrdersTpUslugiView2
     */
    public ViewObjectImpl getOrdersTpUslugiView2() {
        return (ViewObjectImpl) findViewObject("OrdersTpUslugiView2");
    }

    /**
     * Container's getter for OrdersTpUslugiFk1Link1.
     * @return OrdersTpUslugiFk1Link1
     */
    public ViewLinkImpl getOrdersTpUslugiFk1Link1() {
        return (ViewLinkImpl) findViewLink("OrdersTpUslugiFk1Link1");
    }

    /**
     * Container's getter for OrdersTpUslugiView3.
     * @return OrdersTpUslugiView3
     */
    public ViewObjectImpl getOrdersTpUslugiView3() {
        return (ViewObjectImpl) findViewObject("OrdersTpUslugiView3");
    }

    /**
     * Container's getter for OrdersTpUslugiFk3Link1.
     * @return OrdersTpUslugiFk3Link1
     */
    public ViewLinkImpl getOrdersTpUslugiFk3Link1() {
        return (ViewLinkImpl) findViewLink("OrdersTpUslugiFk3Link1");
    }

    /**
     * Container's getter for OrdersTpUslugiView4.
     * @return OrdersTpUslugiView4
     */
    public ViewObjectImpl getOrdersTpUslugiView4() {
        return (ViewObjectImpl) findViewObject("OrdersTpUslugiView4");
    }

    /**
     * Container's getter for OrdersTpUslugiFk2Link1.
     * @return OrdersTpUslugiFk2Link1
     */
    public ViewLinkImpl getOrdersTpUslugiFk2Link1() {
        return (ViewLinkImpl) findViewLink("OrdersTpUslugiFk2Link1");
    }
}

