package ua.divas.model;

import java.sql.Timestamp;

import java.util.UUID;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;

import ua.divas.classes.DivasEntityNoDelete;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 08 17:10:18 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CallLogImpl extends DivasEntityNoDelete {
    @Override
    protected void callId() {
        this.setId(UUID.randomUUID().toString());
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        CallStatus,
        ContactId,
        CompDetId,
        Memo,
        Version,
        CallStatus1,
        CompaignsDetails,
        ContactDetails;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int CALLSTATUS = AttributesEnum.CallStatus.index();
    public static final int CONTACTID = AttributesEnum.ContactId.index();
    public static final int COMPDETID = AttributesEnum.CompDetId.index();
    public static final int MEMO = AttributesEnum.Memo.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int CALLSTATUS1 = AttributesEnum.CallStatus1.index();
    public static final int COMPAIGNSDETAILS = AttributesEnum.CompaignsDetails.index();
    public static final int CONTACTDETAILS = AttributesEnum.ContactDetails.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CallLogImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for CallStatus, using the alias name CallStatus.
     * @return the value of CallStatus
     */
    public String getCallStatus() {
        return (String) getAttributeInternal(CALLSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CallStatus.
     * @param value value to set the CallStatus
     */
    public void setCallStatus(String value) {
        setAttributeInternal(CALLSTATUS, value);
    }

    /**
     * Gets the attribute value for ContactId, using the alias name ContactId.
     * @return the value of ContactId
     */
    public String getContactId() {
        return (String) getAttributeInternal(CONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactId.
     * @param value value to set the ContactId
     */
    public void setContactId(String value) {
        setAttributeInternal(CONTACTID, value);
    }

    /**
     * Gets the attribute value for CompDetId, using the alias name CompDetId.
     * @return the value of CompDetId
     */
    public String getCompDetId() {
        return (String) getAttributeInternal(COMPDETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompDetId.
     * @param value value to set the CompDetId
     */
    public void setCompDetId(String value) {
        setAttributeInternal(COMPDETID, value);
    }

    /**
     * Gets the attribute value for Memo, using the alias name Memo.
     * @return the value of Memo
     */
    public String getMemo() {
        return (String) getAttributeInternal(MEMO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Memo.
     * @param value value to set the Memo
     */
    public void setMemo(String value) {
        setAttributeInternal(MEMO, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the value of Version
     */
    public Timestamp getVersion() {
        return (Timestamp) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Timestamp value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getCallStatus1() {
        return (EntityImpl) getAttributeInternal(CALLSTATUS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setCallStatus1(EntityImpl value) {
        setAttributeInternal(CALLSTATUS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getCompaignsDetails() {
        return (EntityImpl) getAttributeInternal(COMPAIGNSDETAILS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setCompaignsDetails(EntityImpl value) {
        setAttributeInternal(COMPAIGNSDETAILS, value);
    }

    /**
     * @return the associated entity ContactDetailsImpl.
     */
    public ContactDetailsImpl getContactDetails() {
        return (ContactDetailsImpl) getAttributeInternal(CONTACTDETAILS);
    }

    /**
     * Sets <code>value</code> as the associated entity ContactDetailsImpl.
     */
    public void setContactDetails(ContactDetailsImpl value) {
        setAttributeInternal(CONTACTDETAILS, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("ua.divas.model.CallLog");
    }
}

