package ua.divas.view.client;

import java.util.List;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.classes.IndexCharacterObject;
import ua.divas.view.common.KontragentsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 24 20:32:12 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KontragentsViewClient extends ViewUsageImpl implements KontragentsView {
    /**
     * This is the default constructor (do not remove).
     */
    public KontragentsViewClient() {
    }


    public void findKontragentById(String Id) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findKontragentById", new String[] {
                                                                         "java.lang.String" }, new Object[] { Id });
        return;
    }

    public List<IndexCharacterObject> getCharacterIndexList() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getCharacterIndexList", null, null);
        return (List<IndexCharacterObject>) _ret;
    }

    public String getRowStatus(Row row) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getRowStatus", new String[] {
                                                                         "oracle.jbo.Row" }, new Object[] { row });
        return (String) _ret;
    }

    public void removeAllViewCriteria() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "removeAllViewCriteria", null, null);
        return;
    }
}

