package ua.divas.view.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.view.common.VwKontragZamer;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 12 18:09:34 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwKontragZamerClient extends ViewUsageImpl implements VwKontragZamer {
    /**
     * This is the default constructor (do not remove).
     */
    public VwKontragZamerClient() {
    }

    public void paySelectedRows() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "paySelectedRows", null, null);
        return;
    }
}

