package ua.divas.module.client;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.client.remote.ApplicationModuleImpl;

import ua.divas.module.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 16 22:46:51 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void deleteChildren(RowIterator ri, Key selectedNodeKey) {
        Object _ret = this.riInvokeExportedMethod(this, "deleteChildren", new String[] {
                                                  "oracle.jbo.RowIterator", "oracle.jbo.Key" }, new Object[] {
                                                  ri, selectedNodeKey });
        return;
    }
}

