package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 12 18:09:33 EEST 2015
// ---------------------------------------------------------------------
public interface VwKontragZamer extends ViewObject {
    void paySelectedRows();
}

